### ISSUE TITLE
Query not restore float as float after "Fix loss of precision encoding..."

### ISSUE THREAD

**Issue by Dushistov** [couchbase/fleece#221]
Before #207 

if save document like this into couchbase-lite database:

```
        FLEncoder_BeginDict(enc, 1);
        FLEncoder_WriteKey(enc, FLSTR("float"));
        FLEncoder_WriteFloat(enc, 1.5f);
        FLEncoder_EndDict(enc));
```

and then run query like this `SELECT float FROM _default`,

then such asserts were passed without any problem:
```
            FLValue val = FLArrayIterator_GetValue(&e->columns);
            REQUIRED(kFLNumber == FLValue_GetType(val));
            REQUIRED(!FLValue_IsDouble(val));
```

but after #207 , last test failed `REQUIRED(!FLValue_IsDouble(val))`.
So I got double instead of float after #207.

 Is this expected behaviour?

[full_test_code.zip](https://github.com/user-attachments/files/15523077/full_test_code.zip)

**Comment by snej** [comment]
It sounds like the first code block is part of saving a Couchbase Lite document, and the second is after a query that returns data from that document?

Sounds like, if this is a bug, it's something to do with LiteCore, not Fleece.
